
app.cache.prefix: hiauth
app.host: @app.host@

server.port: 8080
spring.thymeleaf.cache: false

logging.level:
  root: @logging.level@
  cn.hiauth: @logging.level@

spring.data.redis:
  host: @redis.host@
  port: @redis.port@
  database: @redis.database@
  password: @redis.password@
  timeout: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: @database.url@
    username: @database.username@
    password: @database.password@
  jpa:
    hibernate:
      ddl-auto: validate  # 自动更新 validate update
    show-sql: true        # 日志中显示sql语句