# 配置springdoc-openapi，用于文档化和访问API
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    # Swagger UI的访问路径
    path: /swagger-ui.html
    # 按字母顺序排序标签
    tags-sorter: alpha
    # 按字母顺序排序操作
    operations-sorter: alpha
  # 配置API文档的访问路径
  api-docs:
    # API文档的访问路径
    path: /v3/api-docs
  # 配置API分组，用于组织和管理API
  group-configs:
    # API分组名称
    - group: 'default'
      # 匹配所有路径
      paths-to-match: '/**'
      # 扫描的包，用于自动发现API
      packages-to-scan: cn.hiauth.server.controller
