
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.hiauth.**.entity, cn.hiauth.**.enums
  global-config:
    db-config:
      id-type: input
      table-prefix:
      table-underline: false
      logic-delete-value: true
      logic-not-delete-value: false
  configuration:
    cache-enabled: true
    cache-expire: 300
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl