server.port: 9000
spring.application.name: gateway
logging.level.root: INFO

# 网关启动方式
spring.main.web-application-type: reactive

# Nacos注册中心配置
spring.cloud.nacos.discovery.server-addr: 192.168.1.250:8848

# 网关路由配置
spring.cloud.gateway.routes:
  - id: ordersvc
    uri: lb://ordersvc/
    predicates:
      - Path=/ordersvc/**
    filters:
      - StripPrefix=1

# HiAuth客户端配置
hiauth.client.gateway:
  issuerUri: http://auth.hiauth.cn
  authorizationUri: ${hiauth.client.gateway.issuerUri}/oauth2/authorize
  tokenUri: ${hiauth.client.gateway.issuerUri}/oauth2/token
  userInfoUri: ${hiauth.client.gateway.issuerUri}/userinfo
  clients:
    himall:
      clientId: himall
      clientSecret: secret
      scope: profile,openid
      redirectUri: http://127.0.0.1:9000/unpapi/himall/oauth2/token/redirect
      # 登录成功后会将accessToken通过这个地址返回给前端
      authSuccessRedirectUri: http://127.0.0.1:9000/ordersvc/api/info
      cachePrefix: himall
      cacheExpire: 2592000
      checkPermission: false

# Redis配置
spring.data.redis:
  host: 192.168.3.143
  port: 26379
  database: 5
  username:
  password: Vking1357!
  timeout: 10000
  connect-timeout: 10000
