
server.port: 8082
app.cache.prefix: hiauth-resource

logging.level:
  root: @logging.level@
  cn.hiauth: @logging.level@

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: @hiauth.auth.host@
  jwk-set-uri: @hiauth.auth.host@/oauth2/jwks
