
server.port: 8081
server.servlet.session.cookie.name: HIMALL_JSESSIONID

spring.thymeleaf.mode: LEGACYHTML5

logging.level:
  root: @logging.level@
  cn.hiauth: @logging.level@

spring:
  security:
    oauth2:
      client:
        registration:
          hiauth-authorization-code:
            provider: hiauth
            client-id: demo-client-id
            client-secret: demo-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
          hiauth-client-credentials:
            provider: hiauth
            client-id: demo-client-id
            client-secret: demo-client-secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: messaging-client-client-credentials
        provider:
          hiauth:
            authorization-uri: @hiauth.auth.host@/oauth2/authorize
            token-uri: @hiauth.auth.host@/oauth2/token
            user-info-uri: @hiauth.resource.host@/api/user/info
            user-name-attribute: name
            jwk-set-uri: @hiauth.auth.host@/oauth2/jwks

hiauth.resource.base-uri: @hiauth.resource.host@
